version: "3.9"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  datawiz:

services:
  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    networks:
      - datawiz
    volumes:
      - "./config/loki.yaml:/etc/loki/config.yaml"

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - datawiz

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=admin_datago
      - GF_SECURITY_ADMIN_PASSWORD=test_datago
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - datawiz
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
  mimir:
    image: grafana/mimir:2.5.0
    command: "-config.file=/etc/mimir/mimir.yaml"
    ports:
      - "9009:9009"
    volumes:
      - "./config/mimir.yaml:/etc/mimir/mimir.yaml"
      - "/tmp/mimir/rules:/tmp/mimir/rules"
    networks:
      - datawiz

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - "9100:9100"
    networks:
      - datawiz

  prometheus:
    image: prom/prometheus:v2.36.2
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    networks:
      - datawiz
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

  alertmanager:
    image: prom/alertmanager:v0.21.0
    user: root
    ports:
      - "9093:9093"
    volumes:
      - "./config/alertmanager.yaml:/etc/alertmanager/config.yml"
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    networks:
      - datawiz