route:
    receiver: smtp

receivers:
    - name: smtp
      email_configs:
          - smarthost: smtp.office365.com:587
            hello: smtp.office365.com
            to:
            from: no-reply@datago.kz
            auth_username: no-reply@datago.kz
            auth_password:
            auth_identity: no-reply@datago.kz
            send_resolved: true
            require_tls: true